---
# tasks file for nfsen
- name: include os-specific variables
  include_vars: "{{ansible_os_family}}.yml"

- include: setup-redhat.yml
  when: ansible_os_family == "RedHat"

- name: set php timezone
  lineinfile: >
      dest=/etc/php.ini
      regexp="^.?date.timezone = "
      line="date.timezone = '{{nfsen_php_timezone}}'"
      insertafter=EOF

- name: ensure nfsen user
  user: name={{nfsen_user}} groups=apache createhome=no

- name: deploy nfsen.conf
  template: src=nfsen.conf.j2 dest=/etc/nfsen.conf
            owner=root group=root mode=0644 backup=yes
  notify: reconfig nfsend

- name: check if nfsen is installed
  stat: path={{nfsen_bindir}}/nfsend
  register: nfsen_stat

- name: check for nfsen archive
  stat: path={{nfsen_src_dir}}/{{nfsen_version}}.tar.gz
  register: nfsen_archive_stat

- name: get nfsen archive
  when: not nfsen_archive_stat.stat.exists
  get_url: url={{nfsen_url}} dest={{nfsen_src_dir}}
  register: nfsen_get_url

- name: extract nfsen archive
  command: >
      chdir={{nfsen_src_dir}}
      creates={{nfsen_src_dir}}/{{nfsen_version}}
      tar xzf {{nfsen_version}}.tar.gz

- name: copy nfsen install patch
  when: nfsen_get_url.changed or not nfsen_stat.stat.exists
  register: nfsen_patch
  copy: >
      src=nfsen-install-no-prompt.patch
      dest={{nfsen_src_dir}}/{{nfsen_version}}/nfsen-install-no-prompt.patch

- name: update install.pl to not prompt
  when: nfsen_patch.changed
  shell: chdir={{nfsen_src_dir}}/{{nfsen_version}}
         patch < nfsen-install-no-prompt.patch

- name: install nfsen
  when: nfsen_get_url.changed or not nfsen_stat.stat.exists
  command: >
      chdir={{nfsen_src_dir}}/{{nfsen_version}}
      ./install.pl /etc/nfsen.conf

- name: check for systemd
  stat: path=/usr/bin/systemctl
  register: stat_systemd

- name: template nfsen.service
  when: stat_systemd.stat.exists
  template: >
      src=nfsen.service.j2
      dest=/etc/systemd/system/nfsen.service
      owner=root group=root mode=0755

- name: template nfsen init script
  when: not stat_systemd.stat.exists
  template: >
      src=nfsen.j2
      dest=/etc/init.d/nfsen
      owner=root group=root mode=0755

- name: deploy porttracker plugin
  command: >-
      chdir={{nfsen_src_dir}}/{{nfsen_version}}
      creates={{item.dest}}/{{item.src}}
      cp contrib/PortTracker/{{item.src}} {{item.dest}}/{{item.src}}
  with_items:
      - { src: PortTracker.pm,  dest: "{{nfsen_vardir}}/plugins" }
      - { src: PortTracker.php, dest: "{{nfsen_htmldir}}/plugins" }

- name: set portsdbdir for porttracker
  lineinfile: >-
      dest={{nfsen_vardir}}/plugins/PortTracker.pm
      regexp="my \$PORTSDBDIR = "
      line="my $PORTSDBDIR = '{{nfsen_portsdbdir}}';"
      insertafter=EOF

- name: create porttracker directory
  file: path={{nfsen_portsdbdir}} state=directory owner={{nfsen_group}} group=apache mode=0775

- name: create porttracker directories
  command: >
      creates={{nfsen_portsdbdir}}/ports.stat
      nftrack -I -d {{nfsen_portsdbdir}}

- name: enable and start nfsend
  service: name=nfsen state=started enabled=yes pattern=bin/nfsend
