---

## from http://steronius.blogspot.ca/2015/04/automatic-malware-filters-for-nfsen.html

- name: malware filters | create directories
  file: "dest={{ item }} state=directory mode=0775 group={{ apache_user }}"
  with_items:
    - "{{ nfsen_vardir }}/profiles-stat/malware/"
    - "{{ nfsen_vardir }}/profiles-stat/malware/Malware-Domain-List"
    - "{{ nfsen_vardir }}/profiles-stat/malware/Hostile_IPs"
    - "{{ nfsen_vardir }}/profiles-stat/malware/ZeusBotNet_CC"

- name: malware filters | copy scripts
  template: "src={{ item.s }} dest={{ nfsen_vardir }}/profiles-stat/malware/{{ item.d }} mode=0755"
  with_items:
    - { s: 'hostile-import-list.sh.j2', d: 'Hostile_IPs/import-list.sh' }
    - { s: 'mdl-import-list.sh.j2', d: 'Malware-Domain-List/import-list.sh' }
    - { s: 'zeus-import-list.sh.j2', d: 'ZeusBotNet_CC/import-list.sh' }

- name: malware filters | add cron entries
  cron: name="nfsen-malwarefilters-{{ item | dirname }}" minute=0
        user="nfsen" job="{{ nfsen_vardir }}/profiles-stat/malware/{{ item }}"
        cron_file=ansible_nfsen-malwarefilters-{{ item | dirname }}
  with_items:
    - 'Hostile_IPs/import-list.sh'
    - 'Malware-Domain-List/import-list.sh'
    - 'ZeusBotNet_CC/import-list.sh'

## TODO: create profile?
##  what about rrd, png and localhost-filter.txt?
##  = not enough
- name: malware filters | create profiles
  template: "src=malwarefilters-profile.dat.j2 dest={{ nfsen_vardir }}/profiles-stat/malware/{{ item }}/profile.dat mode=0664 group={{ apache_user }}"
  with_items:
    - Malware-Domain-List
    - Hostile_IPs
    - ZeusBotNet_CC

- name: malware filters | create filter profiles
  lineinfile: "dest={{ nfsen_vardir }}/profiles-stat/malware/{{ item }}/localhost-filter.txt line='not any' mode=0664 group={{ apache_user }} create=yes"
  with_items:
    - Malware-Domain-List
    - Hostile_IPs
    - ZeusBotNet_CC

