---

## copy? group={{apache_user}}
- name: deploy porttracker plugin
  command: >-
      chdir={{nfsen_src_dir}}/{{nfsen_version}}
      creates={{item.dest}}/{{item.src}}
      cp contrib/PortTracker/{{item.src}} {{item.dest}}/{{item.src}}
  with_items:
      - { src: PortTracker.pm,  dest: "{{nfsen_vardir}}/plugins" }
      - { src: PortTracker.php, dest: "{{nfsen_htmldir}}/plugins" }

- name: set portsdbdir for porttracker
  lineinfile: >-
      dest={{nfsen_vardir}}/plugins/PortTracker.pm
      regexp="my \$PORTSDBDIR = "
      line="my $PORTSDBDIR = '{{nfsen_portsdbdir}}';"
      insertafter=EOF

- name: create porttracker directory
  file: path={{nfsen_portsdbdir}} state=directory owner={{nfsen_group}} group={{apache_user}} mode=0775

- name: create porttracker directories with nftrack
  command: >
      creates={{nfsen_portsdbdir}}/ports.stat
      nftrack -I -d {{nfsen_portsdbdir}}
