---

- name: get sshcure archive
  get_url:
    url: "{{ nfsen_sshcure_url }}"
    dest: "{{ nfsen_src_dir }}/{{ nfsen_sshcure_url | basename }}"
    mode: 0644
    checksum: "{{ nfsen_sshcure_hash }}"
  register: dl
  until: dl is success

- name: uncompress sshcure
#  unarchive: "src={{ nfsen_src_dir }}/SSHCure_v2.4.1.tar.gz dest={{ nfsen_src_dir }} creates={{ nfsen_src_dir }}/SSHCure/readme.txt"
  command: >
      chdir={{ nfsen_src_dir }}
      creates={{ nfsen_src_dir }}/SSHCure/readme.txt
      tar xzf {{ nfsen_src_dir }}/{{ nfsen_sshcure_url | basename }}

- name: sshcure | packages dependencies
  package:
    name: "{{ nfsen_sshcure_deps }}"
    state: present

- block:
    - name: sshcure | install frontend files
    ## FIXME! 'Remote copy does not support recursive copy of directory' and synchronize not supporting remote_src=yes
    #  copy: "src={{ item }} dest={{ nfsen_htmldir }}/plugins mode=0644 group={{ apache_user }} remote_src=yes"
    ## FIXME! fileglob doing only files
    #  with_fileglob:
    #    - "{{ nfsen_src_dir }}/SSHCure/frontend/*"
    ## FIXME! centos7+precise rsync(3.0.9) has no chown/chmod option (ok trusty/rsync3.1)
      command: "rsync -r --chown=root:{{ apache_user }} --chmod=D0755,F0644 {{ item.s }} {{ nfsen_htmldir }}/plugins/ creates={{ item.d }}"
      with_items:
        - { s: "{{ nfsen_src_dir }}/SSHCure/frontend/SSHCure.php", d: "{{ nfsen_htmldir }}/plugins/SSHCure.php" }
        - { s: "{{ nfsen_src_dir }}/SSHCure/frontend/SSHCure", d: "{{ nfsen_htmldir }}/plugins/SSHCure/index.php" }
    - name: sshcure | install backend files
    #  copy: "src={{ item }} dest={{ nfsen_vardir }}/plugins mode=0644 owner={{ apache_user }} group={{ apache_user }} remote_src=yes"
      command: "rsync -r --chown={{ apache_user }}:{{ apache_user }} --chmod=D0755,F0644 {{ item.s }} {{ nfsen_vardir }}/plugins/ creates={{ item.d }}"
    #  with_fileglob:
    #    - "{{ nfsen_src_dir }}/SSHCure/backend/*"
      with_items:
        - { s: "{{ nfsen_src_dir }}/SSHCure/backend/SSHCure.pm", d: "{{ nfsen_vardir }}/plugins/SSHCure.pm" }
        - { s: "{{ nfsen_src_dir }}/SSHCure/backend/SSHCure", d: "{{ nfsen_vardir }}/plugins/SSHCure/config.pm" }
  when: ansible_distribution_release == 'trusty'
- block:
    - name: sshcure | install frontend files
      command: "rsync -r {{ item.s }} {{ nfsen_htmldir }}/plugins/ creates={{ item.d }}"
      with_items:
        - { s: "{{ nfsen_src_dir }}/SSHCure/frontend/SSHCure.php", d: "{{ nfsen_htmldir }}/plugins/SSHCure.php" }
        - { s: "{{ nfsen_src_dir }}/SSHCure/frontend/SSHCure", d: "{{ nfsen_htmldir }}/plugins/SSHCure/index.php" }
    - name: sshcure | install backend files
      command: "rsync -r {{ item.s }} {{ nfsen_vardir }}/plugins/ creates={{ item.d }}"
      with_items:
        - { s: "{{ nfsen_src_dir }}/SSHCure/backend/SSHCure.pm", d: "{{ nfsen_vardir }}/plugins/SSHCure.pm" }
        - { s: "{{ nfsen_src_dir }}/SSHCure/backend/SSHCure", d: "{{ nfsen_vardir }}/plugins/SSHCure/config.pm" }
    - name: sshcure | validate frontend permissions
      file: "dest={{ nfsen_htmldir }}/plugins/SSHCure state=directory mode=0755 owner=root group={{ apache_user }} recurse=yes"
    - name: sshcure | validate backend permissions
      file: "dest={{ nfsen_vardir }}/plugins/SSHCure state=directory mode=0755 owner={{ apache_user }} group={{ apache_user }} recurse=yes"
  when: ansible_distribution_release != 'trusty'

- name: sshcure | check directories exists
  file: dest={{ item }} state=directory mode=0755
  with_items:
    - "{{ nfsen_htmldir }}/plugins/SSHCure/lib/MaxMind"

- name: sshcure | symlink maxmind
  file: "src=/var/maxmind/{{ item }} dest={{ nfsen_htmldir }}/plugins/SSHCure/lib/MaxMind/{{ item }} state=link"
  with_items:
    - GeoLiteCity.dat
    - GeoLiteCityv6.dat

- name: sshcure | review configuration
  replace: "dest={{ nfsen_htmldir }}/plugins/SSHCure/config/config.php regexp={{ item.re }} replace={{ item.rep }} backup=yes"
  with_items:
    - { re: '^\$config\[.nfsen.config-file.\] = .*', rep: "$config['nfsen.config-file'] = '{{ nfsen_confdir }}/nfsen.conf';" }
    - { re: '^\$config\[.backend.path.\] = .*', rep: "$config['backend.path'] = '{{ nfsen_vardir }}/plugins/SSHCure';" }
#    - { re: '^', rep: '' }

## FIXME! apache error.log
## PHP Fatal error:  Call to a member function setAttribute() on a non-object in /var/www/nfsen/plugins/SSHCure/data/actions/data/*.action.php on line 13, referer: http://10.21.181.146/nfsen/plugins/SSHCure/index.php
