---
## https://backports.debian.org/Instructions/

- block:
    - name: Debian | Enable jessie backports
      lineinfile:
        dest: '/etc/apt/sources.list'
        regexp: '^deb http://ftp.debian.org/debian jessie-backports main'
        line: 'deb http://ftp.debian.org/debian jessie-backports main'
        backup: yes

    - name: Debian | install nfdump from backports
      apt:
        name: nfdump
        state: present
## "SystemError: E:The value 'jessie-backports' is invalid for APT::Default-Release as such a release is not available in the sources"
#        default_release: jessie-backports
        update_cache: yes

  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'jessie'
