---
# handlers file for nfsen
- name: restart nfsend
  service: name=nfsend state=restarted

- name: reconfig nfsend
  shell: /usr/bin/yes | {{ nfsen_bindir }}/nfsen reconfig

- name: restart apache
  service:
    name: "{{ apache_svc }}"
    state: restarted

- name: restart rsyslog
  service: name=rsyslog state=restarted
